### PR TITLE
Vinyl Adapter Feel - a complete rewrite

### PR DESCRIPTION
**Pull request by CodeMan99**
# Work in progress

Opening this PR just to see if you have interest in the idea.

## Why

I want to use the module in the future at my place of employment. I need some of the vinyl options to be configurable. I need the module to be well tested.

## What I did

* I stopped using babel in the module code. To me there just is not enough advantage to justify the additional runtime dependency.
* (Hopefully) solved all streaming issues. Streaming hasn't been tested yet.
* Replaced duplexer2 with duplexify. Mostly a drop in replacement and I think duplexify has better error state control.
* Use of `vinyl.stat` property instead of creating the `tarHeader` custom property.
* Added the handling of symlinks.
* Improved the handling of directories.

## What is remaining

* [x] improve the testing, at least on par with [tar-fs](https://github.com/mafintosh/tar-fs/blob/master/test/index.js).
* [x] test streaming. This includes handling files bigger than the highWaterMark, dropping files, and changing content (vinyl.stat.size is no longer true).
* [ ] make the extract class handle back pressure correctly. Namely, the `"drain"` event is a writable feature, not a readable feature, so [this code](https://github.com/chpio/tar-vinyl-stream/blob/0b2b95179c2b83af6157823f1a5b835ef7d34d43/tar-vinyl-stream.es2015.js#L25) will never work.
* [ ] determine if throw a `TypeError` is the correct thing to do for the extract and pack classes. It might be better to say that case is a directory name. `vinyl.isDirectory()` always returns false if the vinyl object has not stat property.

### CODE REVIEW

**Comment by chpio** [comment]
> I want to use the module in the future at my place of employment. I need some of the vinyl options to be configurable. I need the module to be well tested.

Thank you for your great work so far!

> I stopped using babel in the module code. To me there just is not enough advantage to justify the additional runtime dependency.

You're right about `babel-runtime`, but i would like to keep es6-modules for bundlers like [rollup](https://rollupjs.org/) or [webpack](https://webpack.js.org/guides/tree-shaking/). (I think there is a need for this on the "server" side, eg if you want to bundle your app for production, also it's the "next" emerging syntax which is fixing some of the issues with cjs.)

<https://github.com/rollup/rollup/wiki/pkg.module>

**Comment by chpio** [comment]
@CodeMan99 do you want me to merge it as it is right now?

**Comment by CodeMan99** [comment]
> do you want me to merge it as it is right now?

No. I want to at least go about testing some of the streaming cases.

Edit: Right now this is a weekend project for me. So it might be a few weeks before I get to that.

**Comment by CodeMan99** [comment]
@chpio Closing in on finishing this. Do you believe https://github.com/mafintosh/tar-stream/issues/50 is still an issue?

**Comment by chpio** [comment]
have you released it under another name or something on npm? <https://www.npmjs.com/package/@chartiq/vinyl-tar>?

**Comment by CodeMan99** [comment]
> have you released it under another name or something on npm? https://www.npmjs.com/package/@chartiq/vinyl-tar?

Yes, that work was published by ChartIQ. I am no longer employed there as of yesterday.

**Pull request closed without merging**
